apiVersion: batch/v1
kind: Job
metadata:
  name: doscont
spec:
  template:
    spec:
      containers:
      - name: cont1
        image: python:3.6-alpine
        command: ["sh", "-c", "echo contenedor 1 > index.html && python -m http.server 8080"]
      - name: cont2
        image: python:3.6-alpine
        command: ["sh", "-c", "echo contenedor 2 > index.html && python -m http.server 8081"]
      restartPolicy: OnFailure
